import Foundation
import SwiftSyntax
import SwiftSyntaxBuilder

// MARK: - SwiftSyntax Code Generator

/// Generates syntactically correct Swift/SwiftUI source code from the Intermediate Representation.
/// Uses Apple's SwiftSyntax library to programmatically construct the AST.
public final class SwiftSyntaxCodeGenerator: Sendable {

    /// Configuration options for code generation.
    public struct Configuration: Sendable {
        public let indentationWidth: Int
        public let generatePreviewProvider: Bool
        public let generateDocumentation: Bool
        public let accessLevel: AccessLevel

        public init(
            indentationWidth: Int = 4,
            generatePreviewProvider: Bool = true,
            generateDocumentation: Bool = true,
            accessLevel: AccessLevel = .public
        ) {
            self.indentationWidth = indentationWidth
            self.generatePreviewProvider = generatePreviewProvider
            self.generateDocumentation = generateDocumentation
            self.accessLevel = accessLevel
        }

        public enum AccessLevel: String, Sendable {
            case `public` = "public"
            case `internal` = "internal"
            case `private` = "private"
            case `fileprivate` = "fileprivate"
            case package = "package"
        }
    }

    private let configuration: Configuration

    public init(configuration: Configuration = Configuration()) {
        self.configuration = configuration
    }

    // MARK: - Public API

    /// Generates Swift source code for an entire IR.
    public func generate(from ir: IntermediateRepresentation) -> [GeneratedFile] {
        var files: [GeneratedFile] = []

        for sourceFile in ir.sourceFiles {
            let generatedCode = generateSourceFile(sourceFile, globalStyles: ir.globalStyles)
            let outputPath = sourceFile.originalPath
                .replacingOccurrences(of: ".tsx", with: ".swift")
                .replacingOccurrences(of: ".jsx", with: ".swift")

            files.append(GeneratedFile(
                path: outputPath,
                content: generatedCode,
                originalPath: sourceFile.originalPath
            ))
        }

        if !ir.globalStyles.colors.isEmpty || !ir.globalStyles.fonts.isEmpty {
            let designTokens = generateDesignTokens(ir.globalStyles)
            files.append(GeneratedFile(
                path: "DesignTokens.swift",
                content: designTokens,
                originalPath: ""
            ))
        }

        return files
    }

    /// Generates Swift source code for a single component.
    public func generate(component: ComponentIR) -> String {
        let code = generateComponentCode(component)
        return formatCode(code)
    }

    /// Generates Swift source code for a single view node.
    public func generateViewCode(from node: ViewNodeIR) -> String {
        let code = generateViewNodeCode(node, indent: 0)
        return formatCode(code)
    }

    // MARK: - Source File Generation

    private func generateSourceFile(_ sourceFile: SourceFileIR, globalStyles: GlobalStylesIR) -> String {
        var output = generateFileHeader(originalPath: sourceFile.originalPath)

        output += generateImports(sourceFile.imports)
        output += "\n"

        for component in sourceFile.components {
            output += generateComponentCode(component)
            output += "\n"

            if configuration.generatePreviewProvider {
                output += generatePreviewCode(for: component)
                output += "\n"
            }
        }

        return formatCode(output)
    }

    private func generateFileHeader(originalPath: String) -> String {
        let timestamp = ISO8601DateFormatter().string(from: Date())
        return """
        //
        // Generated by React2SwiftUI Canvas
        // Source: \(originalPath)
        // Generated: \(timestamp)
        //
        // This file was automatically generated. Manual edits will be preserved
        // if made within marked regions.
        //

        """
    }

    private func generateImports(_ imports: [ImportIR]) -> String {
        var importLines = ["import SwiftUI"]

        let additionalImports = Set(imports.compactMap { $0.swiftImport })
        for module in additionalImports.sorted() where module != "SwiftUI" {
            importLines.append("import \(module)")
        }

        return importLines.joined(separator: "\n") + "\n"
    }

    // MARK: - Component Code Generation

    private func generateComponentCode(_ component: ComponentIR) -> String {
        var code = ""

        if configuration.generateDocumentation {
            code += generateDocComment(for: component)
        }

        let access = configuration.accessLevel.rawValue

        let genericClause = component.genericParameters.isEmpty ? "" :
            "<\(component.genericParameters.map { "\($0): View" }.joined(separator: ", "))>"

        code += "\(access) struct \(component.name)\(genericClause): View {\n"

        for stateProperty in component.stateProperties {
            code += generateStatePropertyCode(stateProperty)
        }

        if !component.stateProperties.isEmpty && !component.parameters.isEmpty {
            code += "\n"
        }

        for param in component.parameters where !param.isViewBuilder {
            code += generatePropertyCode(param)
        }

        for param in component.parameters where param.isViewBuilder {
            code += generateViewBuilderPropertyCode(param)
        }

        if needsInitializer(component) {
            code += "\n"
            code += generateInitializerCode(component)
        }

        code += "\n"
        code += generateBodyCode(component)

        code += "}\n"

        return code
    }

    private func generateDocComment(for component: ComponentIR) -> String {
        return """
        /// A SwiftUI view generated from React component.
        /// - Note: Original source: \(component.sourceLocation.filePath):\(component.sourceLocation.startLine)

        """
    }

    // MARK: - Property Generation

    private func generateStatePropertyCode(_ property: StatePropertyIR) -> String {
        let access = property.isPrivate ? "private " : ""
        let wrapper = property.wrapper.rawValue
        return "    \(access)\(wrapper) var \(property.name): \(property.type) = \(property.initialValue)\n"
    }

    private func generatePropertyCode(_ param: ParameterIR) -> String {
        var typeStr = param.type

        if param.isBinding {
            typeStr = "@Binding var \(param.name): \(param.type)"
            return "    \(typeStr)\n"
        }

        if param.isOptional {
            typeStr = "\(param.type)?"
        }

        let binding = param.isBinding ? "var" : "let"

        if let defaultValue = param.defaultValue {
            return "    \(binding) \(param.name): \(typeStr) = \(defaultValue)\n"
        }

        return "    \(binding) \(param.name): \(typeStr)\n"
    }

    private func generateViewBuilderPropertyCode(_ param: ParameterIR) -> String {
        return "    @ViewBuilder let \(param.name): () -> \(param.type)\n"
    }

    // MARK: - Initializer Generation

    private func needsInitializer(_ component: ComponentIR) -> Bool {
        component.parameters.contains { $0.isBinding || $0.isViewBuilder }
    }

    private func generateInitializerCode(_ component: ComponentIR) -> String {
        let access = configuration.accessLevel.rawValue
        var code = "    \(access) init(\n"

        let params = component.parameters.enumerated().map { (index, param) -> String in
            generateInitParameterCode(param, isLast: index == component.parameters.count - 1)
        }

        code += params.joined(separator: ",\n")
        code += "\n    ) {\n"

        for param in component.parameters {
            if param.isBinding {
                code += "        self._\(param.name) = \(param.name)\n"
            } else {
                code += "        self.\(param.name) = \(param.name)\n"
            }
        }

        code += "    }\n"

        return code
    }

    private func generateInitParameterCode(_ param: ParameterIR, isLast: Bool) -> String {
        var paramCode = "        "

        if param.isBinding {
            paramCode += "\(param.name): Binding<\(param.type)>"
        } else if param.isViewBuilder {
            paramCode += "@ViewBuilder \(param.name): @escaping () -> \(param.type)"
        } else if param.isOptional {
            paramCode += "\(param.name): \(param.type)?"
            if let defaultValue = param.defaultValue {
                paramCode += " = \(defaultValue)"
            } else {
                paramCode += " = nil"
            }
        } else {
            paramCode += "\(param.name): \(param.type)"
            if let defaultValue = param.defaultValue {
                paramCode += " = \(defaultValue)"
            }
        }

        return paramCode
    }

    // MARK: - Body Generation

    private func generateBodyCode(_ component: ComponentIR) -> String {
        let access = configuration.accessLevel.rawValue
        var code = "    \(access) var body: some View {\n"

        let viewCode = generateViewNodeCode(component.viewHierarchy, indent: 2)
        code += viewCode

        for effect in component.effects {
            code += generateEffectCode(effect, indent: 2)
        }

        code += "    }\n"

        return code
    }

    private func generateEffectCode(_ effect: EffectIR, indent: Int) -> String {
        let indentStr = String(repeating: "    ", count: indent)

        switch effect.modifier {
        case .onAppear:
            return "\(indentStr).onAppear {\n\(indentStr)    \(effect.body)\n\(indentStr)}\n"

        case .onDisappear:
            return "\(indentStr).onDisappear {\n\(indentStr)    \(effect.body)\n\(indentStr)}\n"

        case .onChange:
            guard let dep = effect.dependencies.first else { return "" }
            return "\(indentStr).onChange(of: \(dep)) {\n\(indentStr)    \(effect.body)\n\(indentStr)}\n"

        case .task:
            return "\(indentStr).task {\n\(indentStr)    \(effect.body)\n\(indentStr)}\n"

        default:
            return ""
        }
    }

    // MARK: - View Node Code Generation

    private func generateViewNodeCode(_ node: ViewNodeIR, indent: Int) -> String {
        let indentStr = String(repeating: "    ", count: indent)

        switch node {
        case .view(let viewIR):
            return generateViewCode(viewIR, indent: indent)

        case .text(let textIR):
            return generateTextCode(textIR, indent: indent)

        case .conditional(let conditionalIR):
            return generateConditionalCode(conditionalIR, indent: indent)

        case .loop(let loopIR):
            return generateLoopCode(loopIR, indent: indent)

        case .group(let children):
            return generateGroupCode(children, indent: indent)

        case .empty:
            return "\(indentStr)EmptyView()\n"

        case .unsupported(let unsupportedIR):
            return generateUnsupportedCode(unsupportedIR, indent: indent)
        }
    }

    private func generateViewCode(_ view: ViewIR, indent: Int) -> String {
        let indentStr = String(repeating: "    ", count: indent)
        var code = ""

        let viewName = view.viewType.rawValue

        if view.children.isEmpty && view.initArguments.isEmpty {
            code += "\(indentStr)\(viewName)()"
        } else if view.children.isEmpty {
            let args = generateArgumentsCode(view.initArguments)
            code += "\(indentStr)\(viewName)(\(args))"
        } else {
            if view.initArguments.isEmpty {
                code += "\(indentStr)\(viewName) {\n"
            } else {
                let args = generateArgumentsCode(view.initArguments)
                code += "\(indentStr)\(viewName)(\(args)) {\n"
            }

            for child in view.children {
                code += generateViewNodeCode(child, indent: indent + 1)
            }

            code += "\(indentStr)}"
        }

        for modifier in view.modifiers {
            code += generateModifierCode(modifier)
        }

        code += "\n"

        return code
    }

    private func generateTextCode(_ text: TextIR, indent: Int) -> String {
        let indentStr = String(repeating: "    ", count: indent)
        var code = "\(indentStr)Text("

        code += generateTextContentCode(text.content)
        code += ")"

        for modifier in text.modifiers {
            code += generateModifierCode(modifier)
        }

        code += "\n"

        return code
    }

    private func generateTextContentCode(_ content: TextContentIR) -> String {
        switch content {
        case .literal(let string):
            let escaped = string.replacingOccurrences(of: "\"", with: "\\\"")
            return "\"\(escaped)\""

        case .interpolation(let expression):
            return "\"\\(\(expression))\""

        case .concatenation(let parts):
            let partCodes = parts.map { generateTextContentCode($0) }
            return partCodes.joined(separator: " + ")

        case .localizedKey(let key):
            return "LocalizedStringKey(\"\(key)\")"
        }
    }

    private func generateConditionalCode(_ conditional: ConditionalIR, indent: Int) -> String {
        let indentStr = String(repeating: "    ", count: indent)
        var code = "\(indentStr)if \(conditional.condition) {\n"

        code += generateViewNodeCode(conditional.trueBranch, indent: indent + 1)

        if let falseBranch = conditional.falseBranch {
            code += "\(indentStr)} else {\n"
            code += generateViewNodeCode(falseBranch, indent: indent + 1)
        }

        code += "\(indentStr)}\n"

        return code
    }

    private func generateLoopCode(_ loop: LoopIR, indent: Int) -> String {
        let indentStr = String(repeating: "    ", count: indent)
        var code = "\(indentStr)ForEach(\(loop.arrayExpression), id: \(loop.idKeyPath)) { \(loop.itemVariable) in\n"

        code += generateViewNodeCode(loop.body, indent: indent + 1)

        code += "\(indentStr)}\n"

        return code
    }

    private func generateGroupCode(_ children: [ViewNodeIR], indent: Int) -> String {
        if children.isEmpty {
            let indentStr = String(repeating: "    ", count: indent)
            return "\(indentStr)EmptyView()\n"
        }

        if children.count == 1 {
            return generateViewNodeCode(children[0], indent: indent)
        }

        let indentStr = String(repeating: "    ", count: indent)
        var code = "\(indentStr)Group {\n"

        for child in children {
            code += generateViewNodeCode(child, indent: indent + 1)
        }

        code += "\(indentStr)}\n"

        return code
    }

    private func generateUnsupportedCode(_ unsupported: UnsupportedIR, indent: Int) -> String {
        let indentStr = String(repeating: "    ", count: indent)
        var code = "\(indentStr)// UNSUPPORTED: \(unsupported.reason)\n"
        code += "\(indentStr)// Original: \(unsupported.originalCode)\n"
        if let suggestion = unsupported.suggestedApproach {
            code += "\(indentStr)// Suggestion: \(suggestion)\n"
        }
        code += "\(indentStr)EmptyView()\n"
        return code
    }

    // MARK: - Modifier Code Generation

    private func generateModifierCode(_ modifier: ModifierIR) -> String {
        if let rawCode = modifier.rawCode {
            return rawCode
        }

        let modifierName = modifier.modifier.rawValue

        if modifier.arguments.isEmpty {
            return ".\(modifierName)()"
        }

        let args = generateArgumentsCode(modifier.arguments)
        return ".\(modifierName)(\(args))"
    }

    private func generateArgumentsCode(_ arguments: [InitArgumentIR]) -> String {
        let argStrings = arguments.map { arg -> String in
            let valueCode = generateValueCode(arg.value)
            if let label = arg.label {
                return "\(label): \(valueCode)"
            } else {
                return valueCode
            }
        }

        return argStrings.joined(separator: ", ")
    }

    private func generateValueCode(_ value: ValueIR) -> String {
        switch value {
        case .literal(let string):
            return string

        case .binding(let name):
            return "$\(name)"

        case .expression(let expr):
            return expr

        case .closure(let body):
            return "{ \(body) }"
        }
    }

    // MARK: - Preview Generation

    private func generatePreviewCode(for component: ComponentIR) -> String {
        let previewName = "\(component.name)_Previews"

        var previewInit = "\(component.name)("

        if component.parameters.isEmpty {
            previewInit += ")"
        } else {
            let args = component.parameters.compactMap { param -> String? in
                guard let defaultValue = param.defaultValue ?? defaultPreviewValue(for: param) else {
                    return nil
                }
                return "\(param.name): \(defaultValue)"
            }
            previewInit += args.joined(separator: ", ") + ")"
        }

        return """
        struct \(previewName): PreviewProvider {
            static var previews: some View {
                \(previewInit)
            }
        }

        """
    }

    private func defaultPreviewValue(for param: ParameterIR) -> String? {
        if param.isViewBuilder {
            return "{ Text(\"Preview Content\") }"
        }

        if param.isBinding {
            return ".constant(defaultBindingValue(param.type))"
        }

        switch param.type.lowercased() {
        case "string": return "\"Preview\""
        case "int": return "0"
        case "double", "cgfloat": return "0.0"
        case "bool": return "false"
        case "date": return "Date()"
        case "color": return ".blue"
        default:
            if param.isBinding {
                return ".constant(\"\")"
            }
            if param.isOptional {
                return "nil"
            }
            return nil
        }
    }

    private func defaultBindingValue(_ type: String) -> String {
        switch type.lowercased() {
        case "string": return "\"\""
        case "int": return "0"
        case "double", "cgfloat": return "0.0"
        case "bool": return "false"
        default: return "\"\""
        }
    }

    // MARK: - Design Tokens Generation

    private func generateDesignTokens(_ globalStyles: GlobalStylesIR) -> String {
        var output = """
        //
        // DesignTokens.swift
        // Generated by React2SwiftUI Canvas
        //

        import SwiftUI

        """

        if !globalStyles.colors.isEmpty {
            output += """

            // MARK: - Colors

            extension Color {
            """
            for (name, color) in globalStyles.colors.sorted(by: { $0.key < $1.key }) {
                let sanitizedName = sanitizeIdentifier(name)
                output += """

                    static let \(sanitizedName) = Color(
                        red: \(color.red),
                        green: \(color.green),
                        blue: \(color.blue),
                        opacity: \(color.alpha)
                    )
                """
            }
            output += "\n}\n"
        }

        if !globalStyles.spacing.isEmpty {
            output += """

            // MARK: - Spacing

            enum Spacing {
            """
            for (name, value) in globalStyles.spacing.sorted(by: { $0.key < $1.key }) {
                let sanitizedName = sanitizeIdentifier(name)
                output += "\n    static let \(sanitizedName): CGFloat = \(value)"
            }
            output += "\n}\n"
        }

        if !globalStyles.cornerRadii.isEmpty {
            output += """

            // MARK: - Corner Radii

            enum CornerRadius {
            """
            for (name, value) in globalStyles.cornerRadii.sorted(by: { $0.key < $1.key }) {
                let sanitizedName = sanitizeIdentifier(name)
                output += "\n    static let \(sanitizedName): CGFloat = \(value)"
            }
            output += "\n}\n"
        }

        if !globalStyles.fonts.isEmpty {
            output += """

            // MARK: - Typography

            extension Font {
            """
            for (name, font) in globalStyles.fonts.sorted(by: { $0.key < $1.key }) {
                let sanitizedName = sanitizeIdentifier(name)
                var fontExpr = ".system(size: \(font.size)"
                if let weight = font.weight {
                    fontExpr += ", weight: \(weight)"
                }
                if let design = font.design {
                    fontExpr += ", design: \(design)"
                }
                fontExpr += ")"
                output += "\n    static let \(sanitizedName): Font = \(fontExpr)"
            }
            output += "\n}\n"
        }

        return output
    }

    private func sanitizeIdentifier(_ name: String) -> String {
        var result = name
            .replacingOccurrences(of: "-", with: "_")
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: ".", with: "_")

        if let first = result.first, first.isNumber {
            result = "_" + result
        }

        let keywords = ["class", "struct", "enum", "func", "var", "let", "if", "else", "for", "while", "switch", "case", "default", "return", "break", "continue", "true", "false", "nil", "self", "super", "import", "public", "private", "internal", "fileprivate", "open", "static", "final"]
        if keywords.contains(result) {
            result = "`\(result)`"
        }

        return result
    }

    // MARK: - Code Formatting

    private func formatCode(_ code: String) -> String {
        code
    }
}

// MARK: - Generated File

/// Represents a generated Swift file.
public struct GeneratedFile: Sendable {
    public let path: String
    public let content: String
    public let originalPath: String

    public init(path: String, content: String, originalPath: String) {
        self.path = path
        self.content = content
        self.originalPath = originalPath
    }
}
